version: '3.7'

services:
  nginx:
    image: nginx
    ports:
      - '8000:80'
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../src:/var/www/html
    networks:
      - br0

  php:
    build: ./php
    volumes:
      - ./../src:/var/www/html
    networks:
      - br0
    depends_on:
      - mysql
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - br0
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - ./maildir:/tmp

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    networks:
      - br0
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    restart: always
    ports:
      - '3400:80'
    networks:
      - br0

networks:
  br0:
    driver: bridge

volumes:
  db: {}
  maildir: {}
